# 1. 예외처리(exception handling)

## 1.1 프로그램 오류

**컴파일 에러** - 컴파일 시에 발생하는 에러

**런타임 에러** - 실행 시에 발생하는 에러

**논리적 에러** - 실행은 되지만, 의도와 다르게 동작하는 것



**에러** - 프로그램 코드에 대해서 수습될 수 덦는 심각한 오류

​	ex) `OutOfMemoryError` , `StackOverflowError` 

**예외** - 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류

## 1.2 예외 클래스의 계층구조

1. Exception클래스와 그 자손들

   -> 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외

2. RuntimeException클래스와 그 자손들

   -> 프로그래머의 실수로 발생하는 예외

## 1.3 예외처리하기 - try-catch문

```java
try { 
	// 예외가 발생할 가능성이 있는 문장들을 넣는다.
} catch (Exception1 e1) {
  // Exception1이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
} catch (ExceptionN eN) {
  // ExceptionN이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
}
// 이 중 발생한 예외의 종류와 일치하는 단 한 개의 catch블럭만 수행된다.
```

- try블럭 또는 catch블럭에 또 다른 try-catch문이 포함될 수 있음
- catch블럭 내에 또 하나의 try-catch문이 포함된 경우, 같은 이름의 참소변수 사용 불가

## 1.4 try-catch문에서의 흐름

**try블럭 내에서 예외가 발생한 경우**

1. 발생한 예외와 일치하는 catch블럭이 있는지 확인한다.
2. 일치하는 catch블럭을 찾게 되면, 그 catch블럭 내의 문장들을 수행하고 전체 try-catch문을 빠져나가서 그 다음 문장을 계속해서 수행한다. 만일 일치하는 catch블럭을 찾지 못하면, 예외는 처리되지 못한다.

**try블럭 내에서 예외가 발생하지 않은 경우**

1. catch블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속한다. 

## 1.5 예외의 발생과 catch블럭

**`printStackTrace()` 와 `getMessage()`**

> **`printStackTrace()`** - 예외발생 당시의 호출스택에 있었던 메서드의 정보와 예외 메세지를 화면에 출력한다.
>
> **`getMessage()`** - 발생한 예외클래스의 인스턴스에 저장된 메세지를 얻을 수 있다.  

**멀티 catch블럭**

여러 catch블럭을 `|` 기호를 이용해서, 하나의 catch블럭으로 합칠 수 있음

```java
try {
  ...
} catch (ExceptionA | ExceptionB e) {
  e.printStactTrace();
}
```

예외를 멀티 catch블럭으로 처리하게 되었을 때, 멀티 catch블럭 내에서는 실제로 어떤 예외가 발생한 것인지 알 수 없음

-> 참조변수 e로 멀티 catch블럭에 `|` 기호로 연결된 예외 클래스들의 공통 분모인 조상 예외 클래스에 선언된 멤버만 사용 가능

```java
try {
  ...
} catch (ExceptionA | ExceptionB e) {
  e.methodA();	// 에러. ExceptionA에 선언된 methodA()는 호출불가
  
  if(e instanceof ExceptionA) {
    ExceptionA e1 = (ExceptionA)e;
    e1.methodA();	// OK. ExceptionA에 선언된 메서드 호출가능
  } else {	// if(e instanceof ExceptionB)
  	...
  }
  
  e.printStackTrace();
}
```

## 1.6 예외 발생시키기

> 1. **먼저, 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든 다음**
>
>    Exception e = new Exception("고의로 발생시켰음");
>
> 2. **키워드 throw를 이용해서 예외를 발생시킨다.**
>
>    throw e;

```java
class ExceptionEx9 {
  public static void main(String args[]) {
    try {
      throw new Exception("고의로 발생시켰음.");
    } catch (Exception e) {
      System.out.println("에러 메세지 :" + e.getMessage());
      e.printStackTrace();
    }
    System.out.println("프로그램이 정상 종료되었음.");
  }
}
```

## 1.7 메서드에 예외 선언하기

```java
void method() throws Exception1, Exception2, ... ExceptionN {
  	// 메서드의 내용
}
```

- 메서드에 예외를 선언할 때 일반적으로 RuntimeException클래스는 적지 않음
- 보통 반드시 처리해주어야 하는 예외들만 선언

```java
class ExceptionEx12 {
  public static void main(String[] args) throws Exception {
    method1();	// 같은 클래스내의 static멤버이므로 객체생성없이 직접 호출가능.
  }	// main 메서드의 끝
  
  static void method1() throws Exception {
    method2();
  }	// method1의 끝

	static void method2() throws Exception {
    throw new Exception();
  }	// method2의 끝
}

// 실행결과
java.lang.Exception
  	at ExceptionEx12.method2(ExceptionEx12.java:11)
 		at ExceptionEx12.method1(ExceptionEx12.java:7)
  	at ExceptionEx12.main(ExceptionEx12.java:3)
```

1. 예외가 발생했을 때, 모두 3개의 메서드(main, method1, method2)가 호출스택에 있었으며, 
2. 예외가 발생한 곳은 제일 윗줄에 있는 method2()라는 것과
3. main메서드가 method1()을, 그리고 method1()은 method2()를 호출했다는 것을 알 수 있다.

## 1.8 finally 블럭

예외의 발생여부에 상관없이 실행되어야 할 코드를 포함시킬 목적으로 사용

```java
try {
  // 예외가 발생할 가능성이 있는 문장들을 넣는다.
} catch (Exception1 e1) {
  // 예외처리를 위한 문장을 적는다.
} finally {
  // 예외의 발생여부에 관게없이 항상 수행되어야 하는 문장들을 넣는다.
  // finallly블럭은 try-catch문의 맨 마지막에 위치해야한다.
}
```

## 1.9 자동 자원 반환 - try-with-resources문

```java
try {
  fis = new FileInputStream("score.dat");
  dis = new DataInputStream(fis);
} catch (IOException ie) {
  ie.printStackTrace();
} finally {
  try {
    if(dis!=null)
      dis.close();
  } catch(IOException ie) {
    ie.printStackTrace();
  }
}
```

- Try-with-resources문으로 작성

```java
try (FileInputStream fis = new FileInputStream("score.dat");
    DataInputStream dis = new DataInputStream(fis)) {
  while(true) {
    score = dis.reanInt();
    System.out.println(score);
    sum += score;
  }
} catch (EOFEXception e) {
  System.out.println("점수의 총합은 " + sum + "입니다.");
} catch (IOException ie) {
  ie.printStackTrace();
}
```

try-with-resources문에 의해 자동으로 객체의 close()가 호출될 수 있으려면, 클래스가 AutoCloseable이라는 인터페이스를 구현한 것이어야만 한다.

```java
public interface AutoCloseable {
  void close() throws Exception;
}
```

## 1.10 사용자정의 예외 만들기

```java
class MyException extends Exception {
  MyException(String msg) {	// 문자열을 매개변수로 받는 생성자
    super(msg);	// 조상인 Exception클래스의 생성자를 호출한다.
  }
}
```

- 멤버변수나 메서드를 추가할 수 있음

```java
class MyException extends Exception {
  // 에러 코드 값을 저장하기 위한 필드를 추가했다.
  private final int ERR_CODE:	// 생성자를 통해 초기화한다
  
  MyException(String msg, int errCode) {	// 생성자
    super(msg);
    ERR_CODE = errCode;
  }
  
  MyException(String msg) {	// 생성자	
    this(msg, 100);		// ERR_CODE를 100(기본값)으로 초기화한다.
  }
  
  public int getErrCode() {	// 에러 코드를 얻을 수 있는 메서드도 추가했다.
    return ERR_CODE;	// 이 메서드는 주로 getMessage()와 함께 사용될 것이다.
  }
}
```

## 1.11 예외 되던지기

예외를 처리한 후에 인위적으로 다시 발생시킴

- 하나의 예외에 대해서 예외가 발생한 메서드와 이를 호출한 메서드 양쪽 모두에서 처리해줘야 할 작업이 있을 때 사용
- 예외가 발생할 메서드에서는 try-catch문을 사용해서 예외처리를 해줌과 동시에 메서드의 선언부에 발생할 예외를 throws에 지정해줘야 함

```java
class ExceptionEx17 {
  public static void main(String[] args) {
    try {
      method1();
    } catch (Exception e) {
      System.out.println("main메서드에서 예외가 처리되었습니다.");
    }
  }	// main메서드의 끝
  
  static void method1() throws Exception {
    try {
      throw new Exception();
    } catch (Exception e) {
      System.out.println("method1메서드에서 예외가 처리되었습니다.");
      throw e;
    }
  } 	// method1메서드의 끝
}

// 실행결과
method1메서드에서 예외가 처리되었습니다.
main메서드에서 예외가 처리되었습니다.
```

## 1.12 연결된 예외

예외A가 예외B를 발생시켰다면, A를 B의 원인예외라고 함

```java
try {
  startInstall();	// SpaceException 발생
  copyFiles();
} catch (SpaceException e) {
  InstallException ie = new InstallException("설치중 예외발생");	// 예외 생성
  ie.initCause(e);	// InstallException의 원인 예외를 SpaceException으로 지정
  throw ie;	// InstallException을 발생시킨다.
} catch (MemoryException me) {
  ...
}
```

> **`Throwable initCause(Throwable cause)`** - 지정한 예외를 원인 예외로 등록
>
> **`Throwable getCause()`** - 원인 예외를 반환

